#pragma once

// 주요 오브젝트 관련. (플레이어, 씬, 몬스터 ..)
enum OBJECT_TYPE{
	OBJ_FIRSTFLOOR, OBJ_SECONDFLOOR, OBJ_THIRDFLOOR, OBJ_FOURTHFLOOR, OBJ_FIFTHFLOOR, 
	OBJ_PLAYER,
	OBJ_NPC,
	OBJ_ROPE,
	OBJ_ARROW, OBJ_SKILL_WING, OBJ_SKILL_SHOOT, OBJ_SKILL_SWING, OBJ_SKILL_DRAGON, OBJ_SKILL_FIRE,
	OBJ_MONSTER, OBJ_GRRENMUSH, OBJ_COUPLEMUSH, OBJ_BOSS,
	OBJ_ITEM, OBJ_MONEY,
	OBJ_EFFECT,
	OBJ_UI, OBJ_HPBAR,
	OBJ_INVENTORY,
	OBJ_COMMUNICATION,
	OBJ_MOUSE, OBJ_BUTTON,
	OBJ_MYFONT,
	OBJ_END
};

enum OBJECT_DIR {
	DIR_LEFT, DIR_RIGHT, DIR_END
};

enum SCENE_TYPE {
	SCENE_LOGO, SCENE_MENU, SCENE_EDIT,
	SCENE_FIELD, SCENE_STAGE1, SCENE_MAKINGPLAYER,
	SCENE_END
};

enum PLAYER_STATE {
	PLAYER_STAND, PLAYER_WALK, PLAYER_JUMP, PLAYER_ROPE
	, PLAYER_ATTACK, PLAYER_SWING,
	PLAYER_CRAWLATTACK, PLAYER_CRAWL,
	PLAYER_SHOOT, PLAYER_DAMAGED
};

enum MONSTER_STATE {
	MONSTER_STAND, MONSTER_WALK,/* MONSTER_JUMP, MONSTER_FLY,*/
	MONSTER_ATTACK1, MONSTER_ATTACK2, MONSTER_SKILL1, MONSTER_SKILL2, MONSTER_SKILL3, MONSTER_SKILL4, MONSTER_SKILL5,
	MONSTER_DAMAGED, MONSTER_DEAD
};

enum MOUSE_STATE { MOUSE_BASIC, MOUSE_GRAB };



enum GOLD_ID { GOLD_0, GOLD_1, GOLD_2, GOLD_3 };

enum ARROW_ID { ARROW_BASIC, ARROW_DRAGON };

// 그 외 오브젝트. (지형, 충돌, 폰트 등..)

enum RENDER_TYPE { RENDER_BACKGROUND, RENDER_OBJ, RENDER_EFFECT, RENDER_UI, RENDER_END };

enum LINE_ID { LINE_FIELD, LINE_STAGE1, LINE_STAGE2, LINE_BOSS, LINE_END };

enum COLLISION_ID {
	COL_PLAYER_ROPE,
	COL_PLAYER_FIRSTFLOOR, COL_PLAYER_SECONDFLOOR, COL_PLAYER_THIRDFLOOR, COL_PLAYER_FOURTHFLOOR, COL_PLAYER_FIFTHFLOOR,
	COL_MONSTER_FIRSTFLOOR, COL_MONSTER_SECONDFLOOR, COL_MONSTER_THIRDFLOOR, COL_MONSTER_FOURTHFLOOR, COL_MONSTER_FIFTHFLOOR,
	COL_MONSTER_SKILL, COL_MONSTER_ARROW, COL_MONSTER_SWING, COL_MONSTER_EFFECT,
	COL_BOSS_SKILL, COL_BOSS_ARROW, COL_BOSS_SWING, COL_BOSS_EFFECT,

	COL_PLAYER_MONSTER,
	COL_PLAYER_BOSS,

	COL_PLAYER_ITEM,
	COL_END
};

enum FLOORBOX_ID { FLOORBOX_HEIGHT, FLOORBOX_WIDTH, FLOORBOX_END };


enum FONT_ID { FONTID_DAMAGED, FONTID_ATTACK, FONTID_CRITICAL };

//--------------------------------------------------------------
// 충돌 체크 관련해서 폰트 띄울 때.
enum FONT_TYPE { FONTTYPE_UNIT, FONTTYPE_TENS, FONTTYPE_HUND, FONTTYPE_THOU, FONTTYPE_TENTH };

enum FONT_FLOOR { FONT_FIRSTFLOOR, FONT_SECONDFLOOR, FONT_THIRDFLOOR, FONT_FOURTHFLOOR, FONT_FIFTHFLOOR };

//--------------------------------------------------------------
// ITEM

enum ITEM_TYPE { ACCESSORY, CLOTHES, GLOVE, GOLD, SHOES, WEAPON, PET, PORTION, ITEM_END };
enum ITEM_LEV { BASIC, ADVANDED, EXPERT, LEV_END };
enum ITEM_STATE { EQUIP, UNEQUIP, STATE_END };

//--------------------------------------------------------------
// Player
enum PLAYER_JOB { JOB_STRIKER, JOB_CAPTIN, JOB_END  };